### ISSUE TITLE
recibir argumento de filtrado desde la linea de comando

### ISSUE THREAD

**Issue by christiansalazar** [smerlos/task1#1]
1. se requiere que el programa sea capaz de recibir una entrada en la linea de comando:
     node prueba.js "CHILE VENE"

2. el resultado se muestra considerando algun match del nombre del pais con cualquier de las palabras entregadas en linea de comando. Debe usarse regexp para la comparación, usando la libreria de regexp de la clase [Buffer](https://nodejs.org/api/buffer.html) de nodejs.

3. el ordenamiento del resultado debe hacerse por orden alfabetico.

4. por cada entrada que haga match, invocar una función callback que recibirá dos strings como argumento (el codigo, el nombre del pais), procesará ese dato y lo devolverá sin procesarlo en lo absoluto.

5. solo si es posible: implementar este cambio en un branch separado, para familiarizarte con el esquema de trabajo basado en branch. sino, haz el cambio en una serie de commits ordenados de modo que sea facil hacer seguimiento a lo que haz hecho. Por ejemplo, un commit para hacer el punto1, otro para hacer el punto2 etc..

**Comment by smerlos** [comment]
Añadida capacidad de procesar argumentos desde la linea de comando, permitiendo ver el resultado organizado por orden alfabético.

Se devuelve el resultado sin procesar, solo se organizo dentro de un objeto llamado resultado para su futura manipulación

**Comment by smerlos** [comment]
esto cambios fueron añadidos en una rama nueva llamada "argumentos"

**Comment by christiansalazar** [comment]
cuando haces un commit puedes hacer refwrencia al issud asi:
git commit -a -m "fix issue #1, mensajexxx"
eso causará el cierre del issue 1 automaticamente y ayudará a que se sepa que commit estan involucrados al navegar dentro del issue #1

**Comment by christiansalazar** [comment]
1. que es "key", documentalo y da un ejemplo de qué tiene. asi no hay que correr el codigo para saber que tiene.
2. no se inyecta el uso de "key" en medio del programa. se le pasa como argumento a leerArchivo. ley: ser explícito.
3. veo que ordenas los argumentos para luego buscar en "contenido", no tiene sentido. Se debe escanear cada linea de "contenido" y ver si ambas palabras del argumento estan ahi, si estan entonces se invoca al callback que reporta el match.
4. describir que hace, que recibe y que emite la función "buscarContenido".

ley1: ser explicito.
ley2: documentar y mostrar data de ejemplo.
